name: deploy terraform (infra-tf) - dev only

on:
  push:
    branches: [ main ]
    paths:
      - "infra-tf/**"
      - ".github/workflows/deploy-terraform.yml"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  ENV: dev
  TFVARS: envs/dev.tfvars

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-tf

    steps:
      - uses: actions/checkout@v4

      - name: Ensure tfvars exists
        run: |
          test -f "$TFVARS" || (echo "Missing $TFVARS" && exit 1)

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::939503809934:role/GithubActionsCICDRole
          aws-region: ap-southeast-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init
        run: terraform init -input=false

      - name: Select workspace (dev)
        run: terraform workspace select "$ENV" || terraform workspace new "$ENV"

      - name: Plan (dev)
        run: terraform plan -input=false -no-color -var-file="$TFVARS" -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra-tf/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: [plan]

    # 保留：手工审批
    environment: terraform-apply

    defaults:
      run:
        working-directory: infra-tf

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra-tf

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::939503809934:role/GithubActionsCICDRole
          aws-region: ap-southeast-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init
        run: terraform init -input=false

      - name: Select workspace (dev)
        run: terraform workspace select "$ENV"

      - name: Apply tfplan (dev)
        run: terraform apply -auto-approve tfplan
